// Mocks generated by Mockito 5.0.15 from annotations
// in flutter_app/test/movies_service_test.dart.
// Do not manually edit this file.

import 'package:flutter_app/model/movies_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MoviesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesProvider extends _i1.Mock implements _i2.MoviesProvider {
  MockMoviesProvider() {
    _i1.throwOnMissingStub(this);
  }
}
